ProyectoMVC/Controllers/EjemplosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoMVC.Models;

namespace ProyectoMVC.Controllers
{
    public class EjemplosController : Controller
    {
        // GET: Ejemplos
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SumarNumeros()//sirve para presentar la vista
        {
            return View();
        }
        [HttpPost]
        public ActionResult SumarNumeros(int num1, int num2) {

            int resultado = num1 + num2;
            ViewBag.resultado = resultado;
            return View();
        }

        public ActionResult TablaMultiplicar()//GET:TablaMultiplicar es para representar la vista
        {
            return View();
        }
        [HttpPost]//POST:TablaMultiplicar
        public ActionResult TablaMultiplicar(int numero)
        {
            
            //opcion a:  ENVIAMOS LOS RESULTADOS
            List<int> numeros = new List<int>();
            for (int i = 0; i < 10; i++)
                {
                int resultado = numero * i;
                numeros.Add(resultado);
                //  operacion += "<tr><td>"+ numero + " X "+ i +"</td><td> "+result.ToString()+" </td></tr>";


                }

            //se devuelve la coleccion como modelo
            //enviamos el numero recibido para dibujar en la vista
            ViewBag.Numero = numero;
                return View(numeros);
        }
        //opcion b: 
        public ActionResult TablaMultiplicar2()//get
        {
            return View();
        }
        [HttpPost]
        public ActionResult Tablamultiplicar2(int numero)
        {
            List<Tabla> lista = new List<Tabla>();
            for (int i = 0; i < 10; i++){
                int resultado = numero * i;
                Tabla t = new Tabla();
                t.Resultado = resultado;
                t.Operacion = numero + " X " + i;
                lista.Add(t);
            }
            return View(lista);
        }

       
        public ActionResult Collatz(int? numero)
        {
            //PARA SABER SI TENGO QUE HACER LA CONJETURA
            //O NO, DEBO PREGUNTAR POR NUMERO
            if (numero != null)
            {
                List<int> collatz = new List<int>();
                //AQUI HAY QUE HACER COLLATZ
                while (numero != 1)
                {
                    if (numero % 2 == 0)
                    {
                        numero = numero / 2;
                    }
                    else
                    {
                        numero = numero * 3 + 1;
                    }
                    collatz.Add(numero.GetValueOrDefault());
                }
                //ENVIAMOS A LA VISTA LOS DATOS
                ViewBag.Collatz = collatz;
            }
            //RECIBAMOS EL NUMERO O NO
            //DEBEMOS ENVIAR UNA COLECCION 
            //CON NUMEROS ALEATORIOS A LA VISTA
            Random rnd = new Random();
            //MODELO ALEATORIOS
            List<int> aleatorios = new List<int>();
            for (int i = 1; i <= 5; i++)
            {
                int num = rnd.Next(1, 200);
                aleatorios.Add(num);
            }
            //ENVIAMOS EL MODELO A LA VISTA
            return View(aleatorios);

        }



        public ActionResult MejorJugador()
        {
            return View();
        }
        [HttpPost]
        public ActionResult MejorJugador(Jugador jugador)
        {
            ViewBag.Mensaje = "Su jugador es: " + jugador.Nombre + "con equipo, " 
                + jugador.Equipo + "y con " + jugador.Edad + " años de Edad";
            return View();
        }

    }
}

ProyectoMVC/Views/Ejemplos/Collatz.cshtml
@model List<int>

@{
    ViewBag.Title = "Collatz";
}


<h2>Collatz</h2>
<h2>Conjetura de Collatz</h2>

<ul>
        @foreach (int num in Model)
        {
        <li>
            @Html.ActionLink("Número " + num, "Collatz", "Ejemplos"
                     , new { numero = num }, null)
        </li>
        }
</ul>
<hr />
@if (ViewBag.Collatz != null)
{
    <ul>
        @foreach (int num in ViewBag.Collatz)
        {
            <li>@num</li>
        }
    </ul>
}

ProyectoMVC/Views/Ejemplos/MejorJugador.cshtml
@{
    ViewBag.Title = "MejorJugador";
}

<h2>Mejor Jugador</h2>
<form method="post">
    <div>
        <label>Mejor jugador del mundo:</label>
        <input type="text" name="Nombre" />
    </div>
    <div>
        <label>Mejor equipo:</label>
        <input type="text" name="Equipo" />
    </div>
    <div>
        <label>Edad:</label>
        <input type="text" name="Edad" />
    </div>
    <div>
        <button type="submit">Enviar jugador</button>
    </div>
</form>
<h2 style="color:blueviolet">
    @ViewBag.Mensaje
</h2>

ProyectoMVC/Views/Ejemplos/SumarNumeros.cshtml
@{
    ViewBag.Title = "SumarNumeros";
}

<h2>SumarNumeros</h2>


<form method="post">
    <div>
        <label>SUMAR NUMEROS: </label>
        <input type="text" name="num1" class="form-control" /><br />
        <input type="text" name="num2" class="form-control" /><br />
        <button type="submit" class="btn-success">SUMAR</button>
        <hr />
        <h3 style="color:aquamarine">RESULTADO @ViewBag.Resultado</h3>
    </div>
</form>

ProyectoMVC/Views/Ejemplos/TablaMultiplicar.cshtml
@{
    ViewBag.Title = "TablaMultiplicar";
}

@model List<int>

<h2>TablaMultiplicar</h2>
<form method="post">
    <h1>Introduzca un numero</h1><input type="text" name="numero" class="form-control"/>
    <table>
        <tr><th>OPERACION</th><th>RESULTADO</th></tr>
        
      
    </table><hr />
  <button type="submit" class="btn-success">Tabla Multiplicar</button>

</form>
<hr />
@if(Model != null)
{
    <table class="table-bordered">
        <tr><th>OPERACION</th><th>RESULTADO</th></tr>
        @for(int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@ViewBag.Numero X @(i+1) </td>
                <td>@Model[i] </td>
        </tr>
        }

    </table>
}

ProyectoMVC/Views/Ejemplos/TablaMultiplicar2.cshtml
@model List<ProyectoMVC.Models.Tabla>

@{
    ViewBag.Title = "TablaMultiplicar2";
}

<h2>TablaMultiplicar2</h2>
<form method="post">
    <h1>Introduzca un numero</h1><input type="text" name="numero" class="form-control" />
    <table>
        <tr><th>OPERACION</th><th>RESULTADO</th></tr>


    </table>
    <button type="submit" class="btn-success">Tabla Multiplicar</button>

</form>
@if (Model != null)
{
    <table class="table-bordered">
        <tr><th>OPERACION</th><th>RESULTADO</th></tr>
        @foreach(ProyectoMVC.Models.Tabla t in Model)
        {
            <tr>
                <td>@t.Operacion</td>
                <td>@t.Resultado</td>
            </tr>

        }
       </table>
}