ProyectoMVC/Controllers/InformacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoMVC.Controllers
{
    public class InformacionController : Controller
    {
        // GET: Informacion
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult VistaControladorGET(String app, int? version) //int? Significa que el numero ya admite nullos .ya es opcional la version y nullable                                                                                        
        {
            String dato = version.GetValueOrDefault().ToString();
            if (app != null)
            {
                ViewBag.Mensaje = "Aplicacion: " + app + ", version : " + version.GetValueOrDefault();
            }
            else
            {
                ViewBag.Mensaje = "Aplicacion: " + app + ", version : " + dato;
            }
            return View();
        }
        //GET: VistaControladorPOST
        public ActionResult VistaControladorPOST()
        {
            return View();
        }
        //POST: VistaControladorPOST
        [HttpPost] //importante si no nunca entratrá
        public ActionResult VistaControladorPOST(String nombre)
        {
            ViewBag.Mensaje = "Su nombre es: " + nombre;
            return View();
        }
    }
}

ProyectoMVC/Views/Informacion/VistaControladorGET.cshtml
@{
    ViewBag.Title = "VistaControladorGET";
}

<h2>VistaControladorGET</h2>

<h1>@ViewBag.Mensaje</h1>

@Html.ActionLink("Datos GET", "VistaControladorGET", "Informacion",
                    new { app = "Visual Studio.netbb",version = 2007 }, null)

ProyectoMVC/Views/Informacion/VistaControladorPOST.cshtml
@{
    ViewBag.Title = "VistaControladorPOST";
}

<h2>VistaControladorPOST</h2>

<form method="post">
    <div>
        <label>Introduzca su nombre: </label>
        <input type="text" name="nombre" class="form-control" /><br />
        <button type="submit" class="btn-success">Enviar Datos</button>

        <hr />
        <h3 style="color:aquamarine">@ViewBag.Mensaje</h3>
    </div>
</form>